In [1]:
import numpy as np

In [2]:
list(range(5,16))

[5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [3]:
array_1 = np.array(list(range(5,16)))

In [4]:
array_1

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [5]:
acc = []
for e in array_1:
    acc.append(1/e)

In [6]:
acc

[0.2,
 0.16666666666666666,
 0.14285714285714285,
 0.125,
 0.1111111111111111,
 0.1,
 0.09090909090909091,
 0.08333333333333333,
 0.07692307692307693,
 0.07142857142857142,
 0.06666666666666667]

In [7]:
array_1[6]=12

In [8]:
array_1

array([ 5,  6,  7,  8,  9, 10, 12, 12, 13, 14, 15])

In [9]:
array_2 = np.empty(len(array_1))

In [10]:
array_2

array([            nan, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 1.10555981e-311])

In [11]:
array_2[10]= 1/array_1[10]

In [12]:
array_2

array([       nan, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.06666667])

In [13]:
len(array_1)

11

In [14]:
list(range(0,len(array_1)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [15]:
for i in range(len(array_1)):
    array_2[i] = 1/array_1[i]

In [16]:
array_2

array([0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.08333333, 0.08333333, 0.07692308, 0.07142857,
       0.06666667])

In [17]:
def make_reciprocals(arr):
    """
    takes arr and outputs the reciprocal or arr
    
    """
    array_2 = np.empty(len(arr))
    for i in range(len(arr)):
        array_2[i] = 1/arr[i]
    return array_2    

In [18]:
make_reciprocals(array_2)

array([ 5.,  6.,  7.,  8.,  9., 10., 12., 12., 13., 14., 15.])

In [19]:
%timeit make_reciprocals(array_2)

6.48 µs ± 134 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [20]:
big_array = np.random.randint(1,100,size=1000000)
%timeit make_reciprocals(big_array)

369 ms ± 17.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [21]:
%timeit (1/big_array)

3.42 ms ± 179 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [22]:
x = np.arange(12).reshape(4,3)

In [23]:
np.add(x,2)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [24]:
np.add.accumulate(x)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15],
       [18, 22, 26]])

In [25]:
y=np.arange(5)

In [27]:
array_100 = np.random.randint(1,100,size=10)

In [28]:
list_379 = [array_100[2],array_100[6],array_100[8]]
list_379

[51, 57, 88]

In [29]:
array_100

array([60, 52, 51, 19, 72, 92, 57, 81, 88, 51])

In [30]:
ind = [2,6,8]
list_2 = array_100[ind]

In [31]:
list_2

array([51, 57, 88])

In [32]:
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [33]:
x[2,[2,0,1]]

array([8, 6, 7])

In [40]:
x[1,2]

5